### ISSUE TITLE
doesn't really do much

### ISSUE THREAD

**Issue by zigasaletinger** [skyisle/language-gradle#2]
hello,

with current build (0.187.0) this doesn't really work (partiall coloring in dark theme, none otherwise)

beat reagrds,
Ziga

**Comment by skyisle** [comment]
This package depends on language-groovy. Can you try?

**Comment by aknuds1** [comment]
I was having the same problem, installing language-groovy helped. Isn't it possible to install package deps automatically in Atom?

**Comment by jggc** [comment]
Same thing here I've been wtf'ing for 10 minutes until I think of installing language-groovy. It should at least be documented on this repo's README and the Atom package page.

**Comment by bedge** [comment]
Ditto. Finally stumbled here after 10 min of WTF's and installed language/groovy. 
Looks nice now... So, thanks, I think, but can the deps be updated?

**Comment by jjdonov** [comment]
Either that, or can you explicity put that language-groovy needs to be installed in the README?

**Comment by chefhoobajoob** [comment]
I'd installed language-gradle, found it did nothing with syntax highlighting, then found this issue suggesting I install language-groovy. Uninstalled language-gradle, installed language-groovy, and re-installed language-gradle.

Still, no syntax highlighting.

So, how can I troubleshoot this problem?

**Comment by chefhoobajoob** [comment]
If I remove then re-add the project folder, syntax highlighting starts to work.

**Comment by chefhoobajoob** [comment]
But then, if you happen to install gradle-ci after installing language-groovy and language-gradle, all the syntax highlighting disappears.

**Comment by simonexmachina** [comment]
Hmmn, not feeling the love on this project. Maybe someone should put up their hand to become a contributor/maintainer?

**Comment by wincinderith** [comment]
I'll volunteer myself, I guess I've got the time for it. Plus it'll be a huge time saver in the long run.

**Comment by brunoczim** [comment]
You may try reloading atom after installing `language-groovy`. Press `ctrl + shift + i`, click on the devtools, and then press `f5`. It worked for me.

**Comment by evantill** [comment]
maybe using `https://www.npmjs.com/package/atom-package-dependencies`can force the installation of the gradle plugin ?
